package AllObjects.GUI;

import AllObjects.functionalClasses.MenuFunctionality;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import static com.sun.javafx.scene.control.skin.Utils.getResource;

public class StartPageController{
    @FXML private Button addButton;


    @FXML public void add(ActionEvent event){
        System.out.println("Asd");
    }

    @FXML
    private Button loginbutton;

    // Event Listener on Button[#loginbutton].onAction
    @FXML
    public void login(ActionEvent event) {
        // TODO Autogenerated
    }

    public void addAction(ActionEvent actionEvent) {

        PageOpener.addPage();

    }

    public void displayAction(ActionEvent actionEvent) {

        PageOpener.displayPage();
        ((Node)(actionEvent.getSource())).getScene().getWindow().hide();
    }


    public void chartAction(ActionEvent actionEvent) {
        MenuFunctionality.setIsDetailedInformationChartVisible(false);
        PageOpener.chart();
    }

    public void saveAction(ActionEvent actionEvent) {
            MenuFunctionality.save();
    }

    public void readAction(ActionEvent actionEvent) {
        MenuFunctionality.read();
    }
}
